import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://vtiger.pfklabs.online/');
  await page.getByRole('textbox', { name: 'User name' }).click();
  await page.getByRole('textbox', { name: 'User name' }).fill('flavio.eduardo');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('@PFK2023FE');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Leads' }).click();
  await page.getByRole('button', { name: 'Adicionar Lead' }).click();
  await page.getByRole('cell', { name: 'Selecionar uma Opção Selecionar uma Opção Belo Horizonte Sao Paulo Goiania' }).getByRole('link').click();
  await page.getByRole('listitem').filter({ hasText: /^Treinamento$/ }).click();
  await page.locator('#Leads_editView_fieldName_company').click();
  await page.locator('#Leads_editView_fieldName_company').fill('Purifikar teste');
  await page.locator('#Leads_editView_fieldName_lastname').click();
  await page.locator('#Leads_editView_fieldName_lastname').fill('Flavio1');
  await page.locator('#Leads_editView_fieldName_mobile').click();
  await page.locator('#Leads_editView_fieldName_mobile').fill('31997274053');
  await page.getByRole('cell', { name: 'Selecionar uma Opção Selecionar uma Opção Cadastrado Contato em Andamento' }).getByRole('link').click();
  await page.getByRole('listitem').filter({ hasText: 'Cadastrado' }).click();
  await page.getByRole('link', { name: 'Select an Option' }).click();
  await page.getByRole('listitem').filter({ hasText: 'zz Alderaan' }).click();
  await page.getByRole('row', { name: 'CEP UF Selecionar uma Opção' }).getByRole('link').click();
  await page.locator('#sel8AQ_chzn_o_1').click();
  await page.locator('#Leads_editView_fieldName_cf_995').click();
  await page.locator('#Leads_editView_fieldName_cf_995').fill('Rua teste');
  await page.locator('#Leads_editView_fieldName_cf_765').click();
  await page.locator('#Leads_editView_fieldName_cf_765').fill('sala 501');
  await page.locator('#Leads_editView_fieldName_cf_763').click();
  await page.locator('#Leads_editView_fieldName_cf_763').fill('77');
  await page.locator('#Leads_editView_fieldName_cf_767').click();
  await page.locator('#Leads_editView_fieldName_cf_767').fill('Centro');
  await page.locator('#Leads_editView_fieldName_code').click();
  await page.locator('#Leads_editView_fieldName_code').fill('33251145');
  await page.locator('#Leads_editView_fieldName_description').click();
  await page.locator('#Leads_editView_fieldName_description').fill('Este Lead foi inclu');
  await page.locator('#Leads_editView_fieldName_description').press('Dead');
  await page.locator('#Leads_editView_fieldName_description').fill('Este Lead foi incluído pelo Playwright');
  await page.getByRole('button', { name: 'Salvar' }).nth(1).click();
});